config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  if Rails.env.development?
    # TODO: add admin constraint
    mount Sidekiq::Web => "/sidekiq"
  end

  namespace :users do
    resources :signups, only: %i[new create]
    resources :sessions, only: %i[new create destroy]
    resources :password_resets, only: %i[new create edit update]
    resources :email_confirmations, only: %i[index show create]

    resource :user, only: %i[edit update destroy]
  end

  get "sign-up", to: "users/signups#new", as: :signup
  get "log-in", to: "users/sessions#new", as: :login
  delete "log-out", to: "users/sessions#destroy", as: :logout

  get "info/terms-of-service", to: "static_pages#terms_of_service", as: :terms
  get "info/privacy-policy", to: "static_pages#privacy_policy", as: :privacy_policy

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :page_title %> &middot; Boilerplate</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", 'data-turbo-track': "reload" %>
  <%= javascript_include_tag "application", 'data-turbo-track': "reload", defer: true %>

  <meta property="og:type" content="website">
  <meta property="og:url" content="<%= request.original_url %>">
  <meta property="og:site_name" content="">
  <%= content_for(:head) %>
</head>

<body class="<%= body_class %>">
  <div class="page-wrapper">
    <header class="page-header">
      <div class="page-header__group">
        <a href="/">Hello</a>
      </div>

      <div class="page-header__group">
        <nav role="nav">
          <ul class="page-header__user-nav">
            <% if Current.user.logged_in? %>
              <li><%= link_to Current.user.email, edit_users_user_path %></li>
              <li><%= link_to "Log out", logout_path, data: { turbo_method: :delete } %></li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <main class="page-content">
      <%= render "flashes" -%>

      <%= yield %>
    </main>

    <footer class="page-footer">
      &copy; Copyright <%= Time.zone.today.year %>
    </footer>
  </div>
</body>
</html>